# aula 1
create table compras (id number primary key, valor number, observacoes varchar2(30), data date, recebido char check (recebido in (0,1)));
create sequence id_seq;
insert into compras (id, valor, data, observacoes, recebido) values (id_seq.nextval, 100, '12-MAY-2007', 'Compras de maio', '1');
select * from compras;
select valor, data from compras;
select valor * 3, data from compras;
select valor * 3 as triplo, data from compras;
insert into compras (id, valor, data, observacoes, recebido) values (id_seq.nextval, 150, '15-JUN-2007', 'Compras de junho', '0');
select * from compras;
select valor, data from compras where valor > 100;
select valor, data from compras where valor < 120;
select * from compras where valor < 120 and recebido = '1';
select * from compras where valor < 120 or recebido = '1';
select * from compras where observacoes = 'Compras';
select * from compras where observacoes like 'Compras%';
select * from compras where observacoes like '%de%';
# aula 2
select * from compras;
select * from compras where valor > 200 and valor <= 700;
select * from compras where valor between 200 and 700;
select * from compras where data between '01-JAN-2010' and '01-APR-2010';
update compras set valor = 900 where id = 20;
select * from compras where id = 20;
update compras set valor = 100, observacoes = 'uma compra comum' where data not between '01-JAN-2010' and '01-APR-2010';
select * from compras;
update compras set observacoes = 'datas festivas' where data in ('12-OCT-2010', '25-DEC-2010'. '12-JUN-2010');
select * from compras;
delete from compras where id = 44;
select * from compras;
delete from compras where valor < 50;
# aula 3
desc compras;
insert into compras (id, valor, data, observacoes, recebido) values (id_seq.nextval, 500, '03-AUG-2015', null, '1');
select * from compras;
select * from compras where observacoes is null;
select * from compras where observacoes is not null;
delete from compras where observacoes is null;
select * from compras where observacoes is null;
create tabel pessoas (nome varchar2(100) not null);
alter table compras modify (observacoes varchar2(30) not null);
insert into compras (id, valor, data, observacoes, recebido) values (id_seq.nextval, 500, '03-AUG-2015', null, '1');
desc compras
insert into compras (id, valor, data, observacoes, recebido) values (id_seq.nextval, 500, '03-AUG-2015', 'presente pro filho', '1');
alter table compras modify (recebido char default '0' check (recebido in (0,1)));
insert into compras (id, valor, data, observacoes) values (id_seq.nextval, 500, '03-AUG-2015', 'presente pro filho');
select * from compras;
alter table compras add (forma_pagt varchar2(10) check (forma_pagt in ('boleto', 'dinheiro', 'cartao')));
desc compras;
insert into compras (id, valor, data, observacoes, form_pagt) values (id_seq.nextval, 500, '15-AUG-2015', 'presente pra mae', 'boleto');
select * from compras;
update compras set forma_pagt = 'dinheiro' where forma_pagt is null;
select * from compras;
insert into compras (id, valor, data, observacoes, form_pagt) values (id_seq.nextval, 500, '15-AUG-2015', 'presente pra mae', 'jujuba');
alter table compras rename column forma_pagt to forma_pagto;
desc compras;
# Aula 4
select * from compras;
select sum(valor) from compras;
select sum(valor) from compras where data > '01-JAN-2010';
select avg(valor) from compras;
select count(id) from compras where data between '01-JAN-2010' and '31-DEC-2010';
select sum(valor), avg(valor) from compras;
select sum(valor) as soma, avg(valor) as media from compras;
select sum(valor) from compras where recebido = '1';
select sum(valor) from compras where recebido = '0';
select sum(valor) from compras group by recebido;
select recebido, sum(valor) from compras group by recebido;
select extract(year from data), sum(valor) from compras group by extract(year from data);
select extract(year from data) as ano, sum(valor) as soma from compras group by extract(year from data) order by ano;
